pipeline {
    agent { label 'ubuntu-qa' }

    tools {
        nodejs 'latest'
        jdk 'latest'
    }
    stages {
        stage('Install packages') {
            steps {
                sh 'npm install'
            }
        }
        stage('Run tests') {
            steps {
                withVault([configuration: configuration, vaultSecrets: secrets]) {
                    catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                        sh 'npm run wdio'
                    }
                }
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: 'video/'
        }
    }
}
