name: Run Automation
on:
  push:
    branches:
      - '**'

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install -g eslint
      - run: eslint . --ext .js,.jsx,.ts,.tsx
  
  gherkin-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install -g gherkin-lint
      - run: gherkin-lint

  run-wdio:
    needs: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Dependencies
        run: |
          npm install
      - name: Run Tests
        run: npm run wdio
      # - name: Uploading results
      #   if: always()
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: automation-results
      #     path: tmp
      #     retention-days: 5
